function OFF_AD()
clear all
close all

g.Main = figure('Units','points', ...
... %	'Colormap','gray', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'name', 'OFFAD (OFF_period Automated Detection)', ... 
	'numbertitle', 'off', ...
	'Position',[200 100 500 400], ...
	'Toolbar','none',...
    'Menubar','none',...
    'Tag','OFFAD');

uicontrol(g.Main,'Style', 'pushbutton','String','Open new study',...
    'FontWeight','bold','FontSize',20,...
    'BackgroundColor',[0.3 0.8 0.8],'Units','normalized',...
    'Position',[0.2 0.55 0.6 0.35],...
    'Callback','[OFFDATA] = OFFAD_importdata;');

uicontrol(g.Main,'Style', 'pushbutton','String','Load  previous study',...
    'FontWeight','bold','FontSize',20,...
    'BackgroundColor',[0.3 0.8 0.8],'Units','normalized',...
    'Position',[0.2 0.1 0.6 0.35],'Callback','');

 evalin('base', 'global OFFDATA');
 global OFFDATA
% global OFFDATA_var

%global OFFDATA
%global OFFDATA_var

%if isempty(OFFDATA), OFFDATA = []; end
%if isempty(OFFDATA_var), OFFDATA_var = []; end

