function [OFFDATA]=OFFAD_preset(presetPath)
%
% Preset page: Load data for OFF period detection with defined clustering
% presets from a previous analysis
%
% Author: Christian Harding 2022
% OFF Period Automated Detection (OFFAD) toolbox
% christian.harding@sjc.ox.uk
%
% Requires:
% - Statistics and Machine learning toolbox
% - Signal processing toolbox
%

% Clear previous page
g.Main = findobj('tag', 'OFFAD');
set(g.Main,'Visible','off')

% Figure plot settings
numLine=9;
centres=[0:1/(numLine+1):1];
centres=flip(centres(2:end-1));
centreDif=diff(centres(1:2));
boxHeighthhalf=abs((2.5*centreDif)/6);

% Load presets for OFFDATA structure selected in previous window
OFFDATA=[];
OFFDATAtemp=load(presetPath);


% Callback to load files from directory using GUI
commandload = [ '[filename, filepath] = uigetfile(''*'', ''Select file'');' ...
                    'if filename(1) ~=0,' ...
                    '   set(findobj(''parent'', gcbf, ''tag'', tagtest), ''string'', [ filepath filename ]);' ...
                    'end;' ...
                    'clear filename filepath tagtest;' ];

% Exit callback to store information provided and pass to preclustering
ExitCallback=['importDataVar=findobj(''parent'',gcbf,''type'', ''UIControl'');'...
'importDataVar=importDataVar(end:-1:1);'...
'OFFDATA.datasetname=importDataVar(2).String;'...
'OFFDATA.VSpathin=importDataVar(4).String;'...
'OFFDATA.epochLen=double(string(importDataVar(7).String));'...
'OFFDATA.MUApathin=importDataVar(9).String;'...
'OFFDATA.MUAfs=double(string(importDataVar(12).String));'...
'OFFDATA.MUAunit=importDataVar(14).String;'...
'OFFDATA.LFPpathin=importDataVar(16).String;'...
'OFFDATA.LFPfs=double(string(importDataVar(19).String));'...
'OFFDATA.LFPunit=importDataVar(21).String;'...
'OFFDATA.FiltLFP=double(importDataVar(23).Value);'...
'OFFDATA.clustEval=importDataVar(25).String;'...
'OFFDATA.ignoreChannels=double(string(regexp(importDataVar(27).String,''\d*'',''match'')));'...
'OFFDATA.clustVar1Select=double(string(importDataVar(29).Value));'... %1 = amplitude, 2=power
'OFFDATA.clustVar1Smooth=double(string(importDataVar(31).String));'...
'OFFDATA.clustVar2Select=double(string(importDataVar(32).Value));'... %1 = amplitude, 2=power
'OFFDATA.clustVar2Smooth=double(string(importDataVar(34).String));'...
'OFFDATA.percSamp=double(string(importDataVar(36).String));'... %percentage of signal to sample for cluster thresholding
'OFFDATA.ChannelsFullName=string(importDataVar(38).String);'...
'OFFDATA.Channels=double(string(importDataVar(39).String));'...
'OFFDATA.OptimalK=double(string(importDataVar(40).String));'...
'OFFDATAtemp=load(string(importDataVar(41).UserData));'...
'OFFDATA.BaselineAmp=OFFDATAtemp.OFFDATA.BaselineAmp;'...
'OFFDATA.GMModels=OFFDATAtemp.OFFDATA.GMModels;'...
'set(findobj(''Tag'',''OFFAD_PRESET''),''Visible'',''Off'');'...
'clear importDataVar OFFDATAtemp;'...
'[OFFDATA]=OFFAD_clustering(OFFDATA);'];



% Get screensize to set figure position
screensize = get( groot, 'Screensize' );   
    
% Create figure for data import
g.Preset = figure('name', 'OFFAD (OFF_period Automated Detection) - Preset', ... 
	'numbertitle', 'off', ...
	'Position',[screensize(3)/6,screensize(4)/8,4*screensize(3)/6,screensize(4)/1.4], ...
    'Toolbar','none',...
    'Menubar','none',...
	'Tag','OFFAD_PRESET',...
    'CloseRequestFcn',['set(findobj(''Tag'',''OFFAD''),''Visible'',''on'');'...
    'close(findobj(''Tag'',''OFFAD_PRESET''))']);


%% Line 1
% Create text box to enter dataset name
uicontrol(g.Preset,'Style', 'text','String','Dataset name',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(1)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Preset,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.23 centres(1)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');

%% Line 2
% Create text box to enter path to vigilance state data or open file search GUI
uicontrol(g.Preset,'Style', 'text','String','VSspec path',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(2)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String','',...
    'FontSize',8,...
    'Units','normalized','Tag','PRESET_VSPECPATH',...
    'Position',[0.23 centres(2)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'pushbutton','String','Browse',...
    'FontWeight','bold','FontSize',10,...
    'Units','normalized',...
    'Position',[0.64 centres(2)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback',[ 'tagtest = ''PRESET_VSPECPATH'';' commandload ]);

% Show preset length of epochs used for scoring vigilance states (seconds)
uicontrol(g.Preset,'Style', 'text','String','Epoch Length (s)',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.76 centres(2)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String',OFFDATAtemp.OFFDATA.epochLen,...
    'FontSize',12,...
    'Enable','off',...
    'Units','normalized',...
    'Position',[0.85 centres(2)-boxHeighthhalf 0.1 boxHeighthhalf*2],'Callback','');

%% Line 3
% Create text box to enter path to high frequency neural data (e.g. MUA) or open file search GUI
uicontrol(g.Preset,'Style', 'text','String','MUA path',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(3)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String','',...
    'FontSize',8,...
    'Units','normalized','Tag','PRESET_MUAPATH',...
    'Position',[0.23 centres(3)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'pushbutton','String','Browse',...
    'FontWeight','bold','FontSize',10,...
    'Units','normalized',...
    'Position',[0.64 centres(3)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback',[ 'tagtest = ''PRESET_MUAPATH'';' commandload ]);

% Display preset sampling rate of high frequency neural data
uicontrol(g.Preset,'Style', 'text','String','Fs',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.74 centres(3)-boxHeighthhalf 0.04 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String',OFFDATAtemp.OFFDATA.MUAfs,...
    'FontSize',12,...
    'Enable','off',...
    'Units','normalized',...
    'Position',[0.79 centres(3)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

% Display preset unit of high frequency neural data
uicontrol(g.Preset,'Style', 'text','String','Units',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.86 centres(3)-boxHeighthhalf 0.05 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style','edit','String',OFFDATAtemp.OFFDATA.MUAunit,...
    'FontSize',12,...
    'Enable','off',...
    'Units','normalized',...
    'Position',[0.93 centres(3)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

%% Line 4
% [OPTIONAL] Create text box to enter path to LFP or open file search GUI
uicontrol(g.Preset,'Style', 'text','String','LFP path',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(4)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String','',...
    'FontSize',8,...
    'Units','normalized','Tag','PRESET_LFPPATH',...
    'Position',[0.23 centres(4)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'pushbutton','String','Browse',...
    'FontWeight','bold','FontSize',10,...
    'Units','normalized',...
    'Position',[0.64 centres(4)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback',[ 'tagtest = ''PRESET_LFPPATH'';' commandload ]);

% Display preset LFP sampling rate
uicontrol(g.Preset,'Style', 'text','String','Fs',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.74 centres(4)-boxHeighthhalf 0.04 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String',OFFDATAtemp.OFFDATA.LFPfs,...
    'FontSize',12,...
    'Enable','off',...
    'Units','normalized',...
    'Position',[0.79 centres(4)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

% Display preset LFP units
uicontrol(g.Preset,'Style', 'text','String','Units',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.86 centres(4)-boxHeighthhalf 0.05 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String',OFFDATAtemp.OFFDATA.LFPunit,...
    'FontSize',12,...
    'Enable','off',...
    'Units','normalized',...
    'Position',[0.93 centres(4)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

%% Line 5
% Create button to choose whether to filter the LFP
uicontrol(g.Preset,'Style', 'text','String','Filter LFP (0.5-100Hz)',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(5)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Preset,'Style', 'checkbox',...
    'Value',OFFDATAtemp.OFFDATA.FiltLFP,...
    'Units','normalized',...
    'Position',[0.23 centres(5)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

%% Line 6
% Display preset clustering evaluation method
uicontrol(g.Preset,'Style', 'text','String','Clustering evaluation method',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(6)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String',OFFDATAtemp.OFFDATA.clustEval,...
    'FontSize',12,...
    'Enable','off',...
    'Units','normalized',...
    'Position',[0.23 centres(6)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

%% Line 7
% Display preset rejected channels
uicontrol(g.Preset,'Style', 'text','String','Channels to remove',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(7)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String',strjoin(['[',strjoin(string(OFFDATAtemp.OFFDATA.ignoreChannels)),']']),...
    'FontSize',8,...
    'Enable','off',...
    'Units','normalized',...
    'Position',[0.23 centres(7)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');

%% Line 8
% Display preset number of points for 'heavy smoothing' window
uicontrol(g.Preset,'Style', 'text','String','Smoothing settings',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(8)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
var1options={'Heavy smoothing'};
uicontrol(g.Preset,'Style', 'text','String',var1options,...
    'Value',OFFDATAtemp.OFFDATA.clustVar1Select,...
    'FontSize',12,...
    'Enable','off',...
    'Units','normalized',...
    'Tag','var1',...
    'Position',[0.23 centres(8)-boxHeighthhalf 0.2 boxHeighthhalf*2]);
uicontrol(g.Preset,'Style', 'text','String','Smoothing points +/-',...
    'FontSize',10,...
    'Units','normalized',...
    'Tag','var1Fs',...
    'Position',[0.45 centres(8)-boxHeighthhalf 0.07 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String',OFFDATAtemp.OFFDATA.clustVar1Smooth,...
    'Enable','off',...
    'FontSize',12,...
    'Units','normalized',...
    'Tag','var1Fs',...
    'Position',[0.52 centres(8)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

% Display preset number of points for 'light smoothing' window
var2options={'Light smoothing'};
uicontrol(g.Preset,'Style', 'text','String',var2options,...
    'Value',OFFDATAtemp.OFFDATA.clustVar2Select,...
    'Enable','off',...
    'FontSize',12,...
    'Units','normalized',...
    'Tag','var2',...
    'Position',[0.62 centres(8)-boxHeighthhalf 0.2 boxHeighthhalf*2]);
uicontrol(g.Preset,'Style', 'text','String','Smoothing points +/-',...
    'FontSize',10,...
    'Units','normalized',...
    'Tag','var2Fs',...
    'Position',[0.83 centres(8)-boxHeighthhalf 0.07 boxHeighthhalf*2],'Callback','');
uicontrol(g.Preset,'Style', 'edit','String',OFFDATAtemp.OFFDATA.clustVar2Smooth,...
    'Enable','off',...
    'FontSize',12,...
    'Units','normalized',...
    'Tag','var2Fs',...
    'Position',[0.90 centres(8)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

%% Line 9
% Choose what percentage of NREM data to use to generate the components used for cluster
uicontrol(g.Preset,'Style', 'text','String','Clustering sample size',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(9)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Preset,'Style', 'edit','String','1',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.23 centres(9)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

uicontrol(g.Preset,'Style', 'text','String','%',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.29 centres(9)-boxHeighthhalf-0.02 0.03 boxHeighthhalf*2],'Callback','');

% Invisible uicontrol panels to store data
uicontrol(g.Preset,'Style', 'text','String',OFFDATAtemp.OFFDATA.ChannelsFullName,...
    'FontWeight','bold','FontSize',12,...
    'Visible','off',...
    'Units','normalized',...
    'Position',[0.29 centres(9)-boxHeighthhalf-0.02 0.03 boxHeighthhalf*2],'Callback','');

uicontrol(g.Preset,'Style', 'text','String',OFFDATAtemp.OFFDATA.Channels,...
    'FontWeight','bold','FontSize',12,...
    'Visible','off',...
    'Units','normalized',...
    'Position',[0.29 centres(9)-boxHeighthhalf-0.02 0.03 boxHeighthhalf*2],'Callback','');

uicontrol(g.Preset,'Style', 'text','String',OFFDATAtemp.OFFDATA.OptimalK,...
    'FontWeight','bold','FontSize',12,...
    'Visible','off',...
    'Units','normalized',...
    'Position',[0.29 centres(9)-boxHeighthhalf-0.02 0.03 boxHeighthhalf*2],'Callback','');

% Finish button
uicontrol(g.Preset,'Style', 'pushbutton','String','Done',...
    'FontWeight','bold','FontSize',12,...
    'BackgroundColor',[0.3 0.8 0.8],'Units','normalized',...
    'Position',[0.75 centres(9)-boxHeighthhalf 0.2 boxHeighthhalf*2],...
    'UserData',presetPath,'Callback',ExitCallback);

clear OFFDATAtemp


