function OFFAD_importdata
%
% Import page: Load data for OFF period detection
%
% Author: Christian Harding 2022
% OFF Period Automated Detection (OFFAD) toolbox
% christian.harding@sjc.ox.uk
%
% Requires:
% - Statistics and Machine learning toolbox
% - Signal processing toolbox
%

% Create structure to hold all clustering info
OFFDATA=[];

% Clear previous page
g.Main = findobj('tag', 'OFFAD');
set(g.Main,'Visible','off')

% Figure plot settings
numLine=9;
centres=[0:1/(numLine+1):1];
centres=flip(centres(2:end-1));
centreDif=diff(centres(1:2));
boxHeighthhalf=abs((2.5*centreDif)/6);


% Callback to load files from directory using GUI
commandload = [ '[filename, filepath] = uigetfile(''*'', ''Select file'');' ...
                    'if filename(1) ~=0,' ...
                    '   set(findobj(''parent'', gcbf, ''tag'', tagtest), ''string'', [ filepath filename ]);' ...
                    'end;' ...
                    'clear filename filepath tagtest;' ];

% Get screensize to set figure position
screensize = get( groot, 'Screensize' );   
    
% Create figure for data import
g.Import = figure('name', 'OFFAD (OFF_period Automated Detection) - Import', ... 
	'numbertitle', 'off', ...
	'Position',[screensize(3)/6,screensize(4)/8,4*screensize(3)/6,screensize(4)/1.4], ...
    'Toolbar','none',...
    'Menubar','none',...
	'Tag','OFFAD_IMPORT',...
    'CloseRequestFcn',['set(findobj(''Tag'',''OFFAD''),''Visible'',''on'');'...
    'delete(findobj(''Tag'',''OFFAD_IMPORT''))']);


%% Line 1
% Create text box to enter dataset name
uicontrol(g.Import,'Style', 'text','String','Dataset name',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(1)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.23 centres(1)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');

%% Line 2
% Create text box to enter path to vigilance state data or open file search GUI
uicontrol(g.Import,'Style', 'text','String','VSspec path',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(2)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',8,...
    'Units','normalized','Tag','IMPORT_VSPECPATH',...
    'Position',[0.23 centres(2)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'pushbutton','String','Browse',...
    'FontWeight','bold','FontSize',10,...
    'Units','normalized',...
    'Position',[0.64 centres(2)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback',[ 'tagtest = ''IMPORT_VSPECPATH'';' commandload ]);

% Create text box to enter length of epochs used for scoring vigilance states (seconds)
uicontrol(g.Import,'Style', 'text','String','Epoch length (s)',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.76 centres(2)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.85 centres(2)-boxHeighthhalf 0.1 boxHeighthhalf*2],'Callback','');

%% Line 3
% Create text box to enter path to high frequency neural data (e.g. MUA) or open file search GUI
uicontrol(g.Import,'Style', 'text','String','MUA path',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(3)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',8,...
    'Units','normalized','Tag','IMPORT_MUAPATH',...
    'Position',[0.23 centres(3)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');

% Create text box to enter sampling rate of high frequency neural data
uicontrol(g.Import,'Style', 'pushbutton','String','Browse',...
    'FontWeight','bold','FontSize',10,...
    'Units','normalized',...
    'Position',[0.64 centres(3)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback',[ 'tagtest = ''IMPORT_MUAPATH'';' commandload ]);
uicontrol(g.Import,'Style', 'text','String','Fs',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.74 centres(3)-boxHeighthhalf 0.04 boxHeighthhalf*2],'Callback','');

% Create text box to enter units of high frequency neural data
uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.79 centres(3)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'text','String','Units',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.86 centres(3)-boxHeighthhalf 0.05 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style','popupmenu','String',{'uV','V'},...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.93 centres(3)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

%% Line 4
% [OPTIONAL] Create text box to enter path to LFP or open file search GUI
uicontrol(g.Import,'Style', 'text','String','LFP path',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(4)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',8,...
    'Units','normalized','Tag','IMPORT_LFPPATH',...
    'Position',[0.23 centres(4)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'pushbutton','String','Browse',...
    'FontWeight','bold','FontSize',10,...
    'Units','normalized',...
    'Position',[0.64 centres(4)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback',[ 'tagtest = ''IMPORT_LFPPATH'';' commandload ]);

% [OPTIONAL] Create text box to enter sampling rate of LFP
uicontrol(g.Import,'Style', 'text','String','Fs',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.74 centres(4)-boxHeighthhalf 0.04 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.79 centres(4)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

% [OPTIONAL] Create text box to enter units of LFP
uicontrol(g.Import,'Style', 'text','String','Units',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.86 centres(4)-boxHeighthhalf 0.05 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'popupmenu','String',{'uV','V'},...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.93 centres(4)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

%% Line 5
% Create button to choose whether to filter the LFP 
uicontrol(g.Import,'Style', 'text','String','Filter LFP (0.5-100Hz)',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(5)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'checkbox',...
    'Value',0,...
    'Units','normalized',...
    'Position',[0.23 centres(5)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

%% Line 6
% Create menu to choose the clustering evaluation method
uicontrol(g.Import,'Style', 'text','String','Clustering evaluation method',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(6)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'popupmenu','String',["CalinskiHarabasz","DaviesBouldin"],...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.23 centres(6)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');


%% Line 7
% Create text box to select number of channels to remove from analysis
uicontrol(g.Import,'Style', 'text','String','Channels to remove',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(7)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'edit','String','[ ]',...
    'FontSize',8,...
    'Units','normalized',...
    'Position',[0.23 centres(7)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');

%% Line 8
% Create text box to select number of points for 'heavy smoothing' window
uicontrol(g.Import,'Style', 'text','String','Smoothing settings',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(8)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
var1options={'Heavy smoothing'};
uicontrol(g.Import,'Style', 'text','String',var1options,...
    'FontSize',12,...
    'Units','normalized',...
    'Tag','var1',...
    'Position',[0.23 centres(8)-boxHeighthhalf 0.2 boxHeighthhalf*2]);
uicontrol(g.Import,'Style', 'text','String','Smoothing points +/-',...
    'FontSize',10,...
    'Units','normalized',...
    'Tag','var1Fs',...
    'Position',[0.45 centres(8)-boxHeighthhalf 0.07 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'edit','String','15',...
    'FontSize',12,...
    'Units','normalized',...
    'Tag','var1Fs',...
    'Position',[0.52 centres(8)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

% Create text box to select number of points for 'light smoothing' window
var2options={'Light smoothing'};
uicontrol(g.Import,'Style', 'text','String',var2options,...
    'FontSize',12,...
    'Units','normalized',...
    'Tag','var2',...
    'Position',[0.62 centres(8)-boxHeighthhalf 0.2 boxHeighthhalf*2]);
uicontrol(g.Import,'Style', 'text','String','Smoothing points +/-',...
    'FontSize',10,...
    'Units','normalized',...
    'Tag','var2Fs',...
    'Position',[0.83 centres(8)-boxHeighthhalf 0.07 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'edit','String','5',...
    'FontSize',12,...
    'Units','normalized',...
    'Tag','var2Fs',...
    'Position',[0.90 centres(8)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

%% Line 9
% Choose what percentage of NREM data to use to generate the components used for cluster
uicontrol(g.Import,'Style', 'text','String','Clustering sample size (% NREM)',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(9)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'edit','String','1',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.23 centres(9)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');
uicontrol(g.Import,'Style', 'text','String','%',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.29 centres(9)-boxHeighthhalf-0.02 0.03 boxHeighthhalf*2],'Callback','');


% Create button to progress to preclustering window
uicontrol(g.Import,'Style', 'pushbutton','String','Done',...
    'FontWeight','bold','FontSize',12,...
    'BackgroundColor',[0.3 0.8 0.8],'Units','normalized',...
    'Position',[0.75 centres(9)-boxHeighthhalf 0.2 boxHeighthhalf*2],...
    'Callback',['[OFFDATA,test]=OFFAD_preclustering([findobj(''parent'',gcbf,''type'', ''UIControl'')]);'...
                'if test==1;set(findobj(''Tag'',''OFFAD_IMPORT''),''Visible'',''Off'');try;'...
                '[OFFDATA]=OFFAD_clustering(OFFDATA);catch;delete(findobj(''Tag'',''OFFAD_CLUSTER''));'...
                'set(findobj(''Tag'',''OFFAD_IMPORT''),''Visible'',''on'');end;end;']);





 

 
