function [OFFDATA]=OFFAD_importdata
OFFDATA=[];

%Settings
numLine=9;
centres=[0:1/(numLine+1):1];
centres=flip(centres(2:end-1));
centreDif=diff(centres(1:2));
boxHeighthhalf=abs((2.5*centreDif)/6);


%Function
commandload = [ '[filename, filepath] = uigetfile(''*'', ''Select a text file'');' ...
                    'if filename(1) ~=0,' ...
                    '   set(findobj(''parent'', gcbf, ''tag'', tagtest), ''string'', [ filepath filename ]);' ...
                    'end;' ...
                    'clear filename filepath tagtest;' ];


variableChange = [  'vars=get(findobj(''parent'', gcbf, ''tag'', tag1),''string'');'...
                    'choosevar=get(findobj(''parent'', gcbf, ''tag'', tag1),''value'');'...
                    'if contains(string(vars(choosevar)),''Amplitude'')==1' ...
                    '   set(findobj(''parent'', gcbf, ''tag'', tagfs), ''visible'', ''on'');' ...
                    'else' ...
                    '   set(findobj(''parent'', gcbf, ''tag'', tagfs), ''visible'', ''off'');' ...
                    'end;' ...
                    'clear vars choosevar tag1 tagfs' ];

%Plotting
g.Import = figure('Units','points', ...
... %	'Colormap','gray', ...
	'PaperPosition',[18 180 576/2 432], ...
	'PaperUnits','points', ...
	'name', 'OFFAD (OFF_period Automated Detection)', ... 
	'numbertitle', 'off', ...
	'Position',[200 100 700 400], ...
    'Toolbar','none',...
    'Menubar','none',...
	'Tag','OFFAD_IMPORT');


%% Line 1
uicontrol(g.Import,'Style', 'text','String','Dataset name',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(1)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.23 centres(1)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');

%% Line 2
uicontrol(g.Import,'Style', 'text','String','VSspec path',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(2)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',8,...
    'Units','normalized','Tag','IMPORT_VSPECPATH',...
    'Position',[0.23 centres(2)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'pushbutton','String','Browse',...
    'FontWeight','bold','FontSize',10,...
    'Units','normalized',...
    'Position',[0.64 centres(2)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback',[ 'tagtest = ''IMPORT_VSPECPATH'';' commandload ]);

uicontrol(g.Import,'Style', 'text','String','Epoch Length(s)',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.76 centres(2)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.85 centres(2)-boxHeighthhalf 0.1 boxHeighthhalf*2],'Callback','');

%% Line 3
uicontrol(g.Import,'Style', 'text','String','pNe path',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(3)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',8,...
    'Units','normalized','Tag','IMPORT_PNEPATH',...
    'Position',[0.23 centres(3)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'pushbutton','String','Browse',...
    'FontWeight','bold','FontSize',10,...
    'Units','normalized',...
    'Position',[0.64 centres(3)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback',[ 'tagtest = ''IMPORT_PNEPATH'';' commandload ]);

uicontrol(g.Import,'Style', 'text','String','Fs',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.74 centres(3)-boxHeighthhalf 0.04 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.79 centres(3)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'text','String','Units',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.86 centres(3)-boxHeighthhalf 0.05 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.93 centres(3)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

%% Line 4
uicontrol(g.Import,'Style', 'text','String','LFP path',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(4)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',8,...
    'Units','normalized','Tag','IMPORT_LFPPATH',...
    'Position',[0.23 centres(4)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'pushbutton','String','Browse',...
    'FontWeight','bold','FontSize',10,...
    'Units','normalized',...
    'Position',[0.64 centres(4)-boxHeighthhalf 0.08 boxHeighthhalf*2],'Callback',[ 'tagtest = ''IMPORT_LFPPATH'';' commandload ]);

uicontrol(g.Import,'Style', 'text','String','Fs',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.74 centres(4)-boxHeighthhalf 0.04 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.79 centres(4)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'text','String','Units',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.86 centres(4)-boxHeighthhalf 0.05 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.93 centres(4)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

%% Line 5

uicontrol(g.Import,'Style', 'text','String','Stages to analyse',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(5)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'text','String','NREM',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.3 centres(5)-boxHeighthhalf 0.1 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'checkbox','Value',1,...
    'FontSize',8,...
    'Units','normalized',...
    'Position',[0.4 centres(5)-boxHeighthhalf 0.05 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'text','String','REM',...
   'FontSize',12,...
    'Units','normalized',...
    'Position',[0.5 centres(5)-boxHeighthhalf 0.1 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'checkbox','Value',0,...
    'FontSize',8,...
    'Units','normalized',...
    'Position',[0.6 centres(5)-boxHeighthhalf 0.05 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'text','String','Wake',...
   'FontSize',12,...
    'Units','normalized',...
    'Position',[0.7 centres(5)-boxHeighthhalf 0.1 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'checkbox','Value',0,...
    'FontSize',8,...
    'Units','normalized',...
    'Position',[0.8 centres(5)-boxHeighthhalf 0.05 boxHeighthhalf*2],'Callback','');


%% Line 6

uicontrol(g.Import,'Style', 'text','String','Channels to remove',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(6)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','[ ]',...
    'FontSize',8,...
    'Units','normalized',...
    'Position',[0.23 centres(6)-boxHeighthhalf 0.4 boxHeighthhalf*2],'Callback','');

%% Line 7
uicontrol(g.Import,'Style', 'text','String','Clustering variables',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(7)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

var1options={'Var1 = Amplitude','Var1 = Power'};
uicontrol(g.Import,'Style', 'popup','String',var1options,...
    'FontSize',12,...
    'Units','normalized',...
    'Tag','var1',...
    'Position',[0.23 centres(7)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback',[ 'tagfs = ''var1Fs'';' 'tag1 = ''var1'';' variableChange ]);

uicontrol(g.Import,'Style', 'text','String','Smoothing points',...
    'FontSize',10,...
    'Units','normalized',...
    'Tag','var1Fs',...
    'Position',[0.45 centres(7)-boxHeighthhalf 0.07 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','30',...
    'FontSize',12,...
    'Units','normalized',...
    'Tag','var1Fs',...
    'Position',[0.52 centres(7)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

var2options={'Var2 = Amplitude','Var2 = Power'};
uicontrol(g.Import,'Style', 'popup','String',var2options,...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.62 centres(7)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'text','String','Smoothing points',...
    'FontSize',10,...
    'Units','normalized',...
    'Position',[0.83 centres(7)-boxHeighthhalf 0.07 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','10',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.90 centres(7)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

%% Line 8
uicontrol(g.Import,'Style', 'text','String','Clustering sample size',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.02 centres(8)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'edit','String','10',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.23 centres(8)-boxHeighthhalf 0.06 boxHeighthhalf*2],'Callback','');

uicontrol(g.Import,'Style', 'text','String','%',...
    'FontWeight','bold','FontSize',12,...
    'Units','normalized',...
    'Position',[0.29 centres(8)-boxHeighthhalf-0.02 0.03 boxHeighthhalf*2],'Callback','');

%% Line 9
uicontrol(g.Import,'Style', 'pushbutton','String','Done',...
    'FontWeight','bold','FontSize',12,...
    'BackgroundColor',[0.3 0.8 0.8],'Units','normalized',...
    'Position',[0.75 centres(9)-boxHeighthhalf 0.2 boxHeighthhalf*2],'Callback','[OFFDATA,OFFDATA_var]=OFFAD_clustering([findobj(''parent'',gcbf,''type'', ''UIControl'')]);');



g.Main = findobj('tag', 'OFFAD');
set(g.Main,'Visible','off')
 
 
